# Generated by Django 5.1.2 on 2024-10-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapefile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minaspoint',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='minaspoint',
            name='y',
            field=models.FloatField(),
        ),
    ]
